<!DOCTYPE html>

<html>
<head>
    <title> For Your Calender </title>
    <link rel="stylesheet" type="text/css" href="stdlayout.css">
    <!--<link href='https://fonts.googleapis.com/css?family=Merriweather:400,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>-->
    <!--<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,900' rel='stylesheet' type='text/css'>-->
    <link href='https://fonts.googleapis.com/css?family=Codystar' rel='stylesheet' type='text/css'>
</head>

<header>
    <div class="banner"><img src="banner.png" alt="banner"></div>
</header>
<body>
<main>
    <div id="std">
        <div class="center">

            <form id="addForm" method="post" action="form.ini.php">

                <!-- this field is just required, it would be validated on form submit -->
                <label for='[name="fullname"]'>Full Name :</label>
                <input type="text" name="fullname" placeholder="Names separated by commas..." required/></br>
                <label for='[name="Line1"]'>Address Line 1 - House Name/Number :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                <input type="address" name="Line1" placeholder="Address Line 1" required/></br>
                <label for='[name="Line2"]'>Address Line 2 - Street Name :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                <input type="address" name="Line2" placeholder="Address Line 2"/></br>
                <label for='[name=" Line3"]'>Address Line 3 - City/Town :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                <input type="address" name="Line3" placeholder="City/Town" required/></br>
                <label for='["Line4"]'>Address Line 4 - Post Code
                    :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                <input type="address" name="Line4" placeholder="Post Code" required/></br>

                <label for="message">Message :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                <textarea name="message"></textarea></br>

                <button class="addressbtn" type="submit">
                    Save
                </button>
            </form>

        </div>

    </div>
</body>
</main>


</hmtl>
