<html>

 <head>
   <title> For Your Calender </title>
   <link rel="stylesheet" type="text/css" href="stdlayout.css">
   <!--<link href='https://fonts.googleapis.com/css?family=Merriweather:400,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>-->
   <!--<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,900' rel='stylesheet' type='text/css'>-->
   <link href='https://fonts.googleapis.com/css?family=Codystar' rel='stylesheet' type='text/css'>
 </head>

 <header>
     <html><div class="banner"><img src="banner.png" alt="banner"></img></div></html>
 </header>

  <main>
    <div id="std">
      <div class="center">
          <div class="centertext">
            <p>Ross and Mary</p>
            </div>
          <div class="addressbtn"><a href="address.phtml" title="address">
              <p>Please can we have your address so we can send an invite?</p>
              </a>
          </div>
      </div>

    </div>
  </main>
</hmtl>